# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIy7nGHKiiIXGzAmftoqvn9Dv8IL7h0V
"""

import numpy as np
import matplotlib.pyplot as plt 
import cv2
from google.colab.patches import cv2_imshow

originalImage = cv2.imread('001.jpg')
grayImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2GRAY)
  
(thresh, blackAndWhiteImage) = cv2.threshold(grayImage, 127, 255, cv2.THRESH_BINARY)
a,b=blackAndWhiteImage.shape
#blackAndWhiteImage.resize(b,b)
cv2_imshow(blackAndWhiteImage)
cv2_imshow(originalImage)
#cv2_imshow(grayImage)
cv2.waitKey(0)
cv2.destroyAllWindows()

def getBoxes(eps):
  a, b = blackAndWhiteImage.shape
  #aaa, bbb = int(a/eps), int(b/eps)
  aaa, bbb = eps,eps
  arr = blackAndWhiteImage
  arr_view = arr.reshape(a//aaa, aaa, b//bbb, bbb)
  arr_grid = np.swapaxes(arr_view, 1, 2).reshape(-1, aaa, bbb)
  #for i in range(arr_grid.size):
  #  cv2_imshow(arr_grid[i])
  return arr_grid

eps=[1, 2, 3, 4, 8, 20]
#eps=[1, 2, 4, 8, 16, 20]
N=[0,0,0,0,0,0]

for i in range(6):
  boxes=getBoxes(eps[i])
  for box in boxes:
    if(box.size-cv2.countNonZero(box)>0):
      N[i]+=1
  print(N[i])

lnEps=[0,0,0,0,0,0]
lnN=[0,0,0,0,0,0]
for i in range(6):
  lnEps[i]=np.log(eps[i])
  lnN[i]=np.log(N[i])
  print(lnEps[i])
  print(lnN[i])

coeffs = np.polyfit(lnEps, lnN, 1)
-coeffs[0]