# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WQR8w7c_l8Nz3G5z-rrYfFC4Hyl9ffoy
"""

from PIL import Image
pil_im = Image.open('43.jpg').convert('L')
pil_im.save('043.jpg')

