# -*- coding: utf-8 -*-
"""flab6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0t4LKLqn20IG55Zf5-0NE15mL-ztsi4
"""

import numpy as np
import matplotlib.pyplot as plt 
import cv2
from google.colab.patches import cv2_imshow

originalImage = cv2.imread('10.png')
grayImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2GRAY)
  
#blackAndWhiteImage.resize(b,b)
cv2_imshow(originalImage)
cv2_imshow(grayImage)
cv2.waitKey(0)
cv2.destroyAllWindows()

def ublanket(img):
  k,l=img.shape
  u=np.ndarray(img.shape)
  for i in range(k-1):
    for j in range(l-1):
      u[i][j]=max(img[i][j]+1,max(img[i-1][j],img[i][j-1],img[i+1][j],img[i][j+1]))
  return u

def bblanket(img):
  k,l=img.shape
  b=np.ndarray(img.shape)
  for i in range(k-1):
    for j in range(l-1):
      b[i][j]=min(img[i][j]-1,min(img[i-1][j],img[i][j-1],img[i+1][j],img[i][j+1]))
  return b

def getVol(u,b):
  k,l=u.shape
  vol=0.0
  for i in range(k-1):
    for j in range(l-1):
      vol=vol+u[i][j]-b[i][j]
  return vol

res=[]
betas = [i for i in range(2, 11)]

u1=ublanket(grayImage)
b1=bblanket(grayImage)
for i in range(9):
  u2=ublanket(u1)
  b2=bblanket(b1)
  vol1=getVol(u1,b1)
  vol2=getVol(u2,b2)
  A=(vol2-vol1)/2
  res.append(np.log(A)/np.log(betas[i]))
  u2=u1
  b2=b1

line = plt.plot(betas, res)
plt.xlabel('beta')
plt.ylabel('log(A)/log(delta)')
plt.show()