# -*- coding: utf-8 -*-
"""flab7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T6oAfoBOXEpo3biWmw0TVZs6Dr4gdNSr
"""

import numpy as np
import matplotlib.pyplot as plt 
import cv2
from google.colab.patches import cv2_imshow

originalImage = cv2.imread('10.png')
grayImage = cv2.cvtColor(originalImage, cv2.COLOR_BGR2GRAY)
  
#cv2_imshow(originalImage)
cv2_imshow(grayImage)
cv2.waitKey(0)
cv2.destroyAllWindows()

def ublanket(img):
  k,l=img.shape
  u=np.ndarray(img.shape)
  for i in range(k-1):
    for j in range(l-1):
      u[i][j]=max(img[i][j]+1,max(img[i-1][j],img[i][j-1],img[i+1][j],img[i][j+1]))
  return u

def bblanket(img):
  k,l=img.shape
  b=np.ndarray(img.shape)
  for i in range(k-1):
    for j in range(l-1):
      b[i][j]=min(img[i][j]-1,min(img[i-1][j],img[i][j-1],img[i+1][j],img[i][j+1]))
  return b

def getVol(u,b):
  k,l=u.shape
  vol=0.0
  for i in range(k):
    for j in range(l):
      vol=vol+u[i][j]-b[i][j]
  return vol

def getA(img):
  u1=ublanket(img)
  u2=ublanket(u1)
  u3=ublanket(u2)
  b1=bblanket(img)
  b2=bblanket(b1)
  b3=bblanket(b2)
  vol1=getVol(u1,b1)
  vol2=getVol(u2,b2)
  vol3=getVol(u3,b3)
  A1=(vol2-vol1)/2
  A2=(vol3-vol2)/2
  #D=((np.log(A1)-np.log(A2))/(np.log(2)-np.log(3)))
  #D=2-np.log(A2)/np.log(2)
  return A1, A2

def getD(A1, A2):
  D=((np.log(A1)-np.log(A2))/(np.log(2)-np.log(3)))
  return D

sizes = [20, 30, 50, 100,150,300, 400]

D = []
A = []
for size in sizes:
  tmp=0.0
  count=0.0
  D_=0.0
  A1_=0.0
  A_=0.0
  for i in range(0, grayImage.shape[0], size):
      for j in range(0, grayImage.shape[1], size):
        tmp1, tmp2=getA(grayImage[i:i + size, j: j + size])
        #D_+=getD(tmp1, tmp2)
        A1_+=tmp1;
        A_+=tmp2;
        count+=1.0
        #print(tmp)
      
  D.append(2-np.abs(getD(A1_, A_)))
  A.append(A_)

line = plt.plot(sizes, D)
plt.xlabel('size')
plt.ylabel('D')
plt.show()

line = plt.plot(sizes, A)
plt.xlabel('size')
plt.ylabel('A')
plt.show()

D